Repository rt-net/raspimouse_ros2_examples, pull requests merged in 2020-06, with the labels that each got.

#9 Add line follower examples
  .ci.rosinstall
  .github/workflows/industrial_ci.yml
  CMakeLists.txt
  README.en.md
  README.md
  include/raspimouse_ros2_examples/line_follower_component.hpp
  launch/line_follower.launch.py
  package.xml
  src/line_follower.cpp
  src/line_follower_component.cpp
Labels: enhancement

#10 Merge teleop_joy launch files into one file.
  README.en.md
  README.md
  launch/teleop_joy.launch.py
  launch/teleop_joy_with_mouse.launch.py
Labels: enhancement

#12 update video link in READMEs
  README.en.md
  README.md
Labels: Type: Documentation

#11 Use multi threads in the object tracking example to stabilize the tracking
  launch/object_tracking.launch.py
Labels: Type: Feature

#13 Update Gamepad F710 usage in README
  README.en.md
  README.md
Labels: Type: Documentation
