Repository rt-net/raspimouse_ros2_examples, pull requests merged in 2024-02, with the labels that each got.

#49 カメラライントレースを修正
  README.en.md
  README.md
  include/raspimouse_ros2_examples/camera_line_follower_component.hpp
  launch/camera_line_follower.launch.py
  src/camera_line_follower_component.cpp
Labels: Type: Documentation

#50 Add velocity parameters for camera_line_follower
  README.en.md
  README.md
  src/camera_line_follower_component.cpp
Labels: Type: Feature

#51 Update camera line follower: Set motor power with switch input. Add area_threthold param.
  README.en.md
  README.md
  include/raspimouse_ros2_examples/camera_line_follower_component.hpp
  src/camera_line_follower_component.cpp
Labels: Type: Feature

#52 Camera_FollowerクラスをCameraFollowerに変更
  CMakeLists.txt
  include/raspimouse_ros2_examples/camera_line_follower_component.hpp
  launch/camera_line_follower.launch.py
  src/camera_line_follower_component.cpp
Labels: Type: Refactoring
